language: python
os: linux
python:
  - "2.7"
services:
  - redis-server
  - mysql
before_install:
  - sudo mysql_upgrade
  - sudo service mysql restart
  - sudo mysql -e 'CREATE DATABASE hbuoj DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;'
  - sudo mysql -e "GRANT ALL PRIVILEGES ON hbuoj.* to 'hbuoj'@'localhost' IDENTIFIED BY 'hbuoj'; FLUSH PRIVILEGES;"
  - pip install flake8
install:
  - sudo apt install git gcc g++ make python-dev libxml2-dev libxslt1-dev zlib1g-dev ruby-sass gettext curl
  - wget -q --no-check-certificate -O- https://bootstrap.pypa.io/get-pip.py | sudo python
  - wget -O- https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt install nodejs
  - npm install -g pleeease-cli
  - pip install -r requirements.txt
  - flake8 .
script:
  - ./make_style.sh
  - python manage.py collectstatic
  - python manage.py compilemessages
  - python manage.py compilejsi18n

  - python manage.py migrate
  - python manage.py loaddata navbar
  - python manage.py loaddata language_small
  - python manage.py loaddata demo

  - python manage.py check
  - gunicorn -c gunicorn.py dmoj.wsgi
addons:
  apt:
    update: true
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
