language: python
os: linux
sudo: required
dist: trusty
python:
  - "3.6"
services:
  - docker
  - docker-compose
jobs:
  include:
    - stage: test
      before_install:
        - sudo service mysql stop
        - docker-compose up -d redis db
      install:
        - wget -O- https://deb.nodesource.com/setup_8.x | sudo -E bash -
        - sudo apt-get install -y git gcc g++ make python-dev libxml2-dev libxslt1-dev zlib1g-dev ruby-sass gettext curl nodejs
        - wget -q --no-check-certificate -O- https://bootstrap.pypa.io/get-pip.py | sudo python
        - npm install -g pleeease-cli
        - pip install -r requirements.txt
      script: sh ci/test.sh
    - stage: deploy
      script: sh ci/deploy.sh
addons:
  apt:
    update: true
